import type { Metadata } from "next";
import { Barlow, Barlow_Semi_Condensed } from 'next/font/google'
import "./globals.css";

const barlow = Barlow({
  weight: ['400', '500'], // Add weights as needed
  subsets: ['latin'],
})

const barlowSemiCondensed = Barlow_Semi_Condensed({
  weight: ['600', '700'], // Add weights as needed
  subsets: ['latin'],
}) 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.className} ${barlowSemiCondensed.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
